resource_types:
- name: email
  type: docker-image
  source:
    repository: ((docker_registry))/pcfseceng/email-resource
    insecure_registries: [ ((docker_registry)) ]

resources:
- name: pcf-service-validation
  type: git
  source:
    uri: ((git_service_validation))
    private_key: ((git_key.private_key))
    branch: master
    skip_ssl_verification: true

- name: pipeline_image
  type: docker-image
  source:
    repository: ((docker_registry))/tenjaa/maven-cf
    insecure_registries: [ ((docker_registry)) ]

- name: send-an-email
  type: email
  source:
    smtp:
      host: ((smtp_host))
      port: "25"
      skip_ssl_validation: true
      anonymous: true
    from: "#REDACTED"
    to: [ "#REDACTED" ]

jobs:
- name: push-service-validation-pxa
  plan:
  - get: pcf-service-validation
    trigger: false
  - get: pipeline_image
  - task: push-app
    file: pcf-service-validation/ci/tasks/task.yml
    image: pipeline_image
    params:
      CF_API: ((pxa_cf_api))
      CF_USERNAME: ((pcfadmins_developeruser.username))
      CF_PASSWORD: ((pcfadmins_developeruser.password))
      PCF_ENV: "pxa"
  on_failure:
    put: send-an-email
    params:
      subject_text: "PXA-Service-validation job failed"
      body_text: "PXA Service-validation pipeline failed "

- name: push-service-validation-jcc
  plan:
  - get: pcf-service-validation
    trigger: true
  - get: pipeline_image
  - task: push-app
    file: pcf-service-validation/ci/tasks/task.yml
    image: pipeline_image
    params:
      CF_API: ((jcc_cf_api))
      CF_USERNAME: ((pcfadmins_developeruser.username))
      CF_PASSWORD: ((pcfadmins_developeruser.password))
      PCF_ENV: "jcc"
  on_failure:
    put: send-an-email
    params:
      subject_text: "JCC-Service-validation job failed"
      body_text: "JCC Service-validation pipeline failed "

- name: push-service-validation-jca
  plan:
  - get: pcf-service-validation
    trigger: true
  - get: pipeline_image
  - task: push-app
    file: pcf-service-validation/ci/tasks/task.yml
    image: pipeline_image
    params:
      CF_API: ((jca_cf_api))
      CF_USERNAME: ((pcfadmins_developeruser.username))
      CF_PASSWORD: ((pcfadmins_developeruser.password))
      PCF_ENV: "jca"
  on_failure:
    put: send-an-email
    params:
      subject_text: "JCA-Service-validation job failed"
      body_text: "JCA Service-validation pipeline failed "

- name: push-service-validation-pxc
  plan:
  - get: pcf-service-validation
    trigger: true
  - get: pipeline_image
  - task: push-app
    file: pcf-service-validation/ci/tasks/task.yml
    image: pipeline_image
    params:
      CF_API: ((pxc_cf_api))
      CF_USERNAME: ((pcfadmins_developeruser.username))
      CF_PASSWORD: ((pcfadmins_developeruser.password))
      PCF_ENV: "pxc"
  on_failure:
    put: send-an-email
    params:
      subject_text: "PXC-Service-validation job failed"
      body_text: "PXC Service-validation pipeline failed "

- name: push-service-validation-lva
  plan:
  - get: pcf-service-validation
    trigger: true
  - get: pipeline_image
  - task: push-app
    file: pcf-service-validation/ci/tasks/task.yml
    image: pipeline_image
    params:
      CF_API: ((lva_cf_api))
      CF_USERNAME: ((pcfadmins_developeruser.username))
      CF_PASSWORD: ((pcfadmins_developeruser.password))
      PCF_ENV: "lva"
  on_failure:
    put: send-an-email
    params:
      subject_text: "LVA-Service-validation job failed"
      body_text: "LVA Service-validation pipeline failed "

- name: push-service-validation-lvc
  plan:
  - get: pcf-service-validation
    trigger: true
  - get: pipeline_image
  - task: push-app
    file: pcf-service-validation/ci/tasks/task.yml
    image: pipeline_image
    params:
      CF_API: ((lvc_cf_api))
      CF_USERNAME: ((pcfadmins_developeruser.username))
      CF_PASSWORD: ((pcfadmins_developeruser.password))
      PCF_ENV: "lvc"
  on_failure:
    put: send-an-email
    params:
      subject_text: "LVC-Service-validation job failed"
      body_text: "LVC Service-validation pipeline failed "
